# IMPORTANT: velocity in testing (modifiable)
velocity: 6.0

# IMPORTANT: vel_max and acc_max in training
# not the actual values in testing, ensure consistency between testing and training, please refer to ../policy/primitive.py
vel_max_train: 6.0
acc_max_train: 6.0

# IMPORTANT: weight of costs for unit speed (can be visualized in tensorboard)
wg: 0.12   # guidance
ws: 10.0   # smoothness
wc: 0.1    # collision

# dataset: set image_size = primitive_num × downsampling_factor (×32 for ResNet-18) in each axis
dataset_path: "../dataset"
image_height: 96
image_width: 160

# trajectory and primitive param (Note: traj_time = 2 * radio / vel_max) (can be visualized in rviz)
horizon_num: 5
vertical_num: 3
horizon_camera_fov: 90.0
vertical_camera_fov: 60.0
horizon_anchor_fov: 30.0
vertical_anchor_fov: 30.0
radio_range: 5.0    # planning horizon: 2 * radio_range
radio_num: 1        # only support 1 currently

# safety penalties
d0: 1.2
r: 0.6

# distribution for unit state sampling (can be visualized by 'python ./policy/yopo_dataset.py')
vx_mean_unit: 0.4
vy_mean_unit: 0.0
vz_mean_unit: 0.0
vx_std_unit: 2.0
vy_std_unit: 0.45
vz_std_unit: 0.3
ax_mean_unit: 0.0
ay_mean_unit: 0.0
az_mean_unit: 0.0
ax_std_unit: 0.5
ay_std_unit: 0.5
az_std_unit: 0.3
goal_pitch_std: 10.0  # clip goal_length to: 2 * radio_range; 10% probability [0, 2 * radio_range]
goal_yaw_std: 20.0

# extend the map to avoid trajectory exceeding bounds (especially in z-axis) and treating the sky outside the map as obstacle
map_expand_min: [0, 0, 0.2]
map_expand_max: [0, 0, 6.0]